### ISSUE TITLE
Fetch is undefined

### ISSUE THREAD

**Issue by evanshortiss** [ExodusMovement/coinmarketcap#2]
Hi! When using this module in Node.js I receive a `ReferenceError: fetch is not defined` error. Is this only meant to be used in React Native or similar environments?

**Comment by fanatid** [comment]
sorry, lack of documentation here
https://github.com/ExodusMovement/cryptocompare#usage

**Comment by evanshortiss** [comment]
My bad. Totally missed the obvious! 

Defining a global is not ideal, perhaps the module could be instantiated with fetch and other options in the future?

```js
const api = coinmarketcap({
  // future options can go here...
  fetch: require('node-fetch')
})
```
